name: Fly Deploy
on:
  push:
    branches:
      - main    # change to main if needed
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
    - uses: actions/checkout@v4

    - name: Set Working Directory
      run: echo "WORKING_DIR=$(pwd)/uproach_me" >> $GITHUB_ENV  # Exporting the working directory to the environment

    - name: Change to Working Directory
      run: |
        echo "Current working directory:"
        echo $WORKING_DIR  # Print the working directory for debugging
        ls "$WORKING_DIR"   # List contents of the working directory
      env:
        WORKING_DIR: ${{ env.WORKING_DIR }}  # Pass the variable to this step

    - name: Set up Node.js with the version 18
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Install dependencies
      run: npm install next react react-dom
      working-directory: ${{ env.WORKING_DIR }}  # Use the working directory

    - name: Build app
      run: npm run build
      working-directory: ${{ env.WORKING_DIR }}  # Use the working directory

    - name: Deploy to Fly.io
      run: flyctl deploy --remote-only
      working-directory: ${{ env.WORKING_DIR }}  # Use the working directory
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_NEXT_TOKEN }}